config/routes.rb
Rails.application.routes.draw do
  resources :task_lists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "start#page"
  require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task_list.rb
class TaskList < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/start_controller.rb
class StartController < ApplicationController
  def page
  end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :set_task_list, only: [:show, :edit, :update, :destroy]

  # GET /task_lists
  # GET /task_lists.json
  def index
    @task_lists = TaskList.all
  end

  # GET /task_lists/1
  # GET /task_lists/1.json
  def show
  end

  # GET /task_lists/new
  def new
    @task_list = TaskList.new
  end

  # GET /task_lists/1/edit
  def edit
  end

  # POST /task_lists
  # POST /task_lists.json
  def create
    @task_list = TaskList.new(task_list_params)

    respond_to do |format|
      if @task_list.save
        NewTasksNotificationWorker.perform_in(1.minutes, @task_list.id, @task_list.priority)
        format.html { redirect_to @task_list, notice: 'Task list was successfully created.' }
        format.json { render :show, status: :created, location: @task_list }
      else
        format.html { render :new }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_lists/1
  # PATCH/PUT /task_lists/1.json
  def update
    respond_to do |format|
      if @task_list.update(task_list_params)
        format.html { redirect_to @task_list, notice: 'Task list was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_list }
      else
        format.html { render :edit }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_lists/1
  # DELETE /task_lists/1.json
  def destroy
    @task_list.destroy
    respond_to do |format|
      format.html { redirect_to task_lists_url, notice: 'Task list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_list
      @task_list = TaskList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_list_params
      params.require(:task_list).permit(:task, :priority, :email_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestAppCap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/start/page.html.erb
<h1>Great if you see this on EC2</h1>

app/views/task_lists/_form.html.erb
<%= form_with(model: task_list, local: true) do |form| %>
  <% if task_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task_list.errors.count, "error") %> prohibited this task_list from being saved:</h2>

      <ul>
        <% task_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task %>
    <%= form.text_field :task %>
  </div>

    <div class="field">
      <%= form.label :email_id %>
      <%= form.text_field :email_id %>
    </div>
  <div class="field">
    <%= form.label :priority %>
    <%= form.number_field :priority %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/task_lists/edit.html.erb
<h1>Editing Task List</h1>

<%= render 'form', task_list: @task_list %>

<%= link_to 'Show', @task_list %> |
<%= link_to 'Back', task_lists_path %>

app/views/task_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Lists</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Priority</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_lists.each do |task_list| %>
      <tr>
        <td><%= task_list.task %></td>
        <td><%= task_list.priority %></td>
        <td><%= task_list.email_id %></td>
        <td><%= link_to 'Show', task_list %></td>
        <td><%= link_to 'Edit', edit_task_list_path(task_list) %></td>
        <td><%= link_to 'Destroy', task_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task List', new_task_list_path %>

app/views/task_lists/new.html.erb
<h1>New Task List</h1>

<%= render 'form', task_list: @task_list %>

<%= link_to 'Back', task_lists_path %>

app/views/task_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @task_list.task %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task_list.priority %>
</p>

<p>
  <strong>Email:</strong>
  <%= @task_list.email_id %>
</p>

<%= link_to 'Edit', edit_task_list_path(@task_list) %> |
<%= link_to 'Back', task_lists_path %>